### ISSUE TITLE
Error loading psycopg2 module: No module named psycopg2

### ISSUE THREAD

**Issue by martysaxton** [ikatson/docker-reviewboard#39]
make build && make run

Everything seemed to work in docker, but as soon as I hit http://localhost:8000 I get an empty response, and the following in the console:

```
reviewboard_1  |     __import__(name)
reviewboard_1  |   File "/opt/venv/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 25, in <module>
reviewboard_1  |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
reviewboard_1  | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2
```

I tried adding psycopg2 to the pip command in the Dockerfile, and it looked like pip installed it, but I still got the same result.

**Comment by ikatson** [comment]
Thanks @martysaxton , fixed this in master
