### ISSUE TITLE
Please release 3.0.11

### ISSUE THREAD

**Issue by apollux** [ikatson/docker-reviewboard#45]
Hi Igor,

I would like to update our reviewboard instance to 3.0.11. Could you please release a 3.0.11 tag?

Cheers,
André

**Comment by ikatson** [comment]
Hi @apollux would appreciate if you create a PR as I don't have time to work in this repo at the moment.

**Comment by apollux** [comment]
just verified, no PR needed. Matter of `RB_VERSION=3.0.11 make` and pushing of the resulting tags. Do I miss something?

**Comment by ikatson** [comment]
All done, latest and 3.0.11 released

**Comment by apollux** [comment]
Thanks!

Would you be open for a pull request adding travis ci integration, so that you could release by merging a pull request?

Not making any promises, but I might find some time for that during the holidays.

Cheers,
André

**Comment by ikatson** [comment]
Well currently dockerhub is configured to build on 2 things:
- a branch is created that matches a regex "number.number.number"
- a push to master has occured

So all I needed to do is to create a branch called 3.0.11 and push it
