### ISSUE TITLE
Multi-threaded single process configuration

### ISSUE THREAD

**Issue by BenStaveleyTaylor** [ikatson/docker-reviewboard#47]
I posted a [problem on the ReviewBoard user support forum](https://groups.google.com/forum/#!topic/reviewboard/SOn5c1BFE00) and this was part of the reply from Christian Hammond:

> I looked at the Docker image and I suspect part of what's happening is that uwsgi (set up in the image) is running multi-threaded but only with a single process. This can lead to blocking issues. You're really going to want to update that to use multiple processes, for things like this. Maybe start with 10, go up from there. You'll have to determine what numbers are best for your scale (and how many Docker instances you plan to run). It doesn't look like the image natively supports customizing this, so you'll probably have to fork the image.

If you agree it is an issue with this Docker image, could it be changed, or at least made configurable? Thanks.

**Comment by ikatson** [comment]
Hi @BenStaveleyTaylor 

feel free to open a PR. You can add smth like this:

```processes=%k``` to uwsgi.ini. I believe it will set the number of processes to the number of cores, according to [uwsgi magic variables docs](https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#magic-variables).

Please test and make sure it works, thanks.

**Comment by BenStaveleyTaylor** [comment]
Thanks, I did this. I'll leave it to you to decide whether to accept it. It didn't affect the container performance for me, but if it is theoretically better then great.

-- Ben.

**Comment by ikatson** [comment]
Merged that PR
