### ISSUE TITLE
psql login fails

### ISSUE THREAD

**Issue by ohle** [ikatson/docker-reviewboard#49]
To reproduce: in current master, `docker-compose up`

PSQL login continually fails:

```
reviewboard_1  | psql: FATAL:  password authentication failed for user "reviewboard"
reviewboard_1  | Postgres is unavailable - sleeping
postgres_1     | 2020-03-20 10:59:07.222 UTC [51] FATAL:  password authentication failed for user "reviewboard"
postgres_1     | 2020-03-20 10:59:07.222 UTC [51] DETAIL:  Password does not match for user "reviewboard".
postgres_1     |        Connection matched pg_hba.conf line 95: "host all all all md5"
```

... ad infinitum

**Comment by praveeno** [comment]
![image](https://user-images.githubusercontent.com/19618730/81490972-08e9fc00-92a6-11ea-8206-221c9c81b992.png)
same with me

**Comment by ikatson** [comment]
Should be fixed with https://github.com/ikatson/docker-reviewboard/commit/216770a8beffcf05b2b71a79f63f01d8a0482481

**Comment by praveeno** [comment]
thanks @ikatson , such a easy way to solve this, but i didn't get this.
