### ISSUE TITLE
Location of SSH key

### ISSUE THREAD

**Issue by easybe** [ikatson/docker-reviewboard#8]
At least on my installation Review Board puts the generated or uploaded private key into `/root/.ssh`. Should't it go into `/.ssh`? Or what is `/.ssh` for? No doubt it must be persistent and thus stored in a volume. Am I missing something? Why do I seem to be the only one with this problem?

Cheers,
Ezra.

**Comment by ikatson** [comment]
Hi, sorry for responding for too long. I changed the way the image works underneath, it's now based on centos:7 and is installed using RPM packages instead of compiling during the build.

Looks like it's /root/.ssh now, I updated the README accordingly.
Please test with the new Dockerfile

**Comment by easybe** [comment]
OK, thanx.

CentOS? Why not use Alpine, it's what is used for Docker images these days...

**Comment by ikatson** [comment]
The reason behind using centos is that it has pre-built relatively fresh ReviewBoard packages. 
See the [offical installation page](https://www.reviewboard.org/docs/manual/dev/admin/installation/linux/#if-you-re-running-centos-red-hat-etc)
